class Stores
	def self.list
		[
			{
				dnis: '12057586913',
				name: 'TUSCALOOSA - MCFARLAND BLVD E',
			 	open_hours: {
					sunday: ['8:00am','8:00pm'],
					monday: ['8:00am','8:00pm'],
					tuesday: ['8:00am','8:00pm'],
					wednesday: ['8:00am','8:00pm'],
					thursday: ['8:00am','8:00pm'],
					friday: ['8:00am','8:00pm'],
					saturday: ['8:00am','8:00pm'],
				},
				addr_city: 'Tuscaloosa',
				addr_street: '1400 McFarland Blvd E',
				addr_state: 'AL',
				addr_zip: '35405',
				division: 'east',
				district: '1',
				commisary: 'com1',
				depot: '100',
				kiosk: 'false',
				retail: 'true',
				closed_for_reason: '_NIL_',
				timezone: 'EST',
				media_files: {
					'hurricane_1': '_NIL_',
					'hurricane_2': '_NIL_',
					'hurricane_3': '_NIL_',
					'covid': '_NIL_',
					'temp_closure': '_NIL_',
			 	}
			},	 	
			{
				dnis: '14792730168',
				name: 'BENTONVILLE - SE WALTON BLVD',
			 	open_hours: {
					sunday: ['5:30am','10:00pm'],
					monday: ['5:30am','10:00pm'],
					tuesday: ['5:30am','10:00pm'],
					wednesday: ['5:30am','10:00pm'],
					thursday: ['5:30am','10:00pm'],
					friday: ['5:30am','11:00pm'],
					saturday: ['5:30am','11:00pm'],
				},
				addr_city: 'Bentonville',
				addr_street: '1502 SE Walton Blvd',
				addr_state: 'AR',
				addr_zip: '72712',
				division: 'east',
				district: '2',
				commisary: 'com2',
				depot: '200',
				kiosk: 'false',
				retail: 'true',							
				closed_for_reason: '_NIL_',
				timezone: 'CST',
				media_files: {
					'hurricane_1': '_NIL_',
					'hurricane_2': '_NIL_',
					'hurricane_3': '_NIL_',
					'covid': '_NIL_',
					'temp_closure': '_NIL_',
			 	}
			},
			{
				dnis: '14803253663',
				name: 'MESA - E SUPERSTITION SPRINGS',
			 	open_hours: {
					sunday: ['5:30am','10:00pm'],
					monday: ['5:30am','10:00pm'],
					tuesday: ['5:30am','10:00pm'],
					wednesday: ['5:30am','10:00pm'],
					thursday: ['5:30am','10:00pm'],
					friday: ['5:30am','11:00pm'],
					saturday: ['5:30am','11:00pm'],
				},
				addr_city: 'Mesa',
				addr_street: '6626 E Superstition Springs Blvd',
				addr_state: 'AZ',
				addr_zip: '85206',
				division: 'west',
				district: '2',
				commisary: 'com2',
				depot: '300',
				kiosk: 'false',
				retail: 'true',						
				closed_for_reason: '_NIL_',
				timezone: 'MST',
				media_files: {
					'hurricane_1': '_NIL_',
					'hurricane_2': '_NIL_',
					'hurricane_3': '_NIL_',
					'covid': '_NIL_',
					'temp_closure': '_NIL_',
			 	}
			},	
			{
				dnis: '14804830821',
				name: 'SCOTTSDALE - SHEA Blvd',
			 	open_hours: {
					sunday: ['5:30am','10:00pm'],
					monday: ['5:30am','10:00pm'],
					tuesday: ['5:30am','10:00pm'],
					wednesday: ['5:30am','10:00pm'],
					thursday: ['5:30am','10:00pm'],
					friday: ['5:30am','11:00pm'],
					saturday: ['5:30am','11:00pm'],
				},
				addr_city: 'Scottsdale',
				addr_street: '7055 E Shea Blvd',
				addr_state: 'AZ',
				addr_zip: '85206',
				division: 'west',
				district: '2',
				commisary: 'com2',
				depot: '100',
				kiosk: 'true',
				retail: 'false',						
				closed_for_reason: '_NIL_',
				timezone: 'MST',
				media_files: {
					'hurricane_1': '_NIL_',
					'hurricane_2': '_NIL_',
					'hurricane_3': '_NIL_',
					'covid': '_NIL_',
					'temp_closure': '_NIL_',
			 	}
			},
			{
				dnis: '19195679827',
				name: 'FUQUAY VARINA - N JUDD PKWY',
			 	open_hours: {
					sunday: ['8:00am','8:00pm'],
					monday: ['8:00am','8:00pm'],
					tuesday: ['8:00am','8:00pm'],
					wednesday: ['8:00am','8:00pm'],
					thursday: ['8:00am','8:00pm'],
					friday: ['8:00am','8:00pm'],
					saturday: ['8:00am','8:00pm'],
				},
				addr_city: 'Fuquay Varina',
				addr_street: '7055 E Shea Blvd',
				addr_state: 'NC',
				addr_zip: '27526',
				division: 'central',
				district: '3',	
				commisary: 'com1',
				depot: '100',
				kiosk: 'false',
				retail: 'true',							
				closed_for_reason: '_NIL_',
				timezone: 'EST',
				media_files: {
					'hurricane_1': '_NIL_',
					'hurricane_2': '_NIL_',
					'hurricane_3': '_NIL_',
					'covid': '_NIL_',
					'temp_closure': '_NIL_',
			 	}
			},			
		]
	end
end